/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./../Components/ActionMessage.vue')['default']
    ActionSection: typeof import('./../Components/ActionSection.vue')['default']
    AddContactDialog: typeof import('./../Components/Dialogs/Partials/AddContactDialog.vue')['default']
    AppLayout: typeof import('./../Layouts/AppLayout.vue')['default']
    ApplicationLogo: typeof import('./../Components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./../Components/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./../Components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./../Components/AuthenticationCardLogo.vue')['default']
    AuthLayout: typeof import('./../Layouts/AuthLayout.vue')['default']
    Banner: typeof import('./../Components/Banner.vue')['default']
    Checkbox: typeof import('./../Components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./../Components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./../Components/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./../Components/DangerButton.vue')['default']
    DialogModal: typeof import('./../Components/DialogModal.vue')['default']
    Dropdown: typeof import('./../Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./../Components/DropdownLink.vue')['default']
    FormSection: typeof import('./../Components/FormSection.vue')['default']
    InputError: typeof import('./../Components/InputError.vue')['default']
    InputLabel: typeof import('./../Components/InputLabel.vue')['default']
    ListCaseDialog: typeof import('./../Components/Dialogs/ListCaseDialog.vue')['default']
    Modal: typeof import('./../Components/Modal.vue')['default']
    MyContactsDialog: typeof import('./../Components/Dialogs/MyContactsDialog.vue')['default']
    NavLink: typeof import('./../Components/NavLink.vue')['default']
    Paginator: typeof import('./../Components/Paginator.vue')['default']
    PanelLayout: typeof import('./../Layouts/PanelLayout.vue')['default']
    PrimaryButton: typeof import('./../Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./../Components/ResponsiveNavLink.vue')['default']
    SearchField: typeof import('./../Components/SearchField.vue')['default']
    SecondaryButton: typeof import('./../Components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./../Components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./../Components/SectionTitle.vue')['default']
    TextInput: typeof import('./../Components/TextInput.vue')['default']
    ThemeProvide: typeof import('./../Components/ThemeProvide.vue')['default']
    VCheck: typeof import('vuetify/components')['VCheck']
    Welcome: typeof import('./../Components/Welcome.vue')['default']
  }
}
